# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ironarachne/culturegen
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd cmd/culturegend
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ironarachne/culturegend:$TAG -t ironarachne/culturegend:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/culturegend:$TAG
          docker push ironarachne/culturegend:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: master